-- 코드를 입력하세요
-- 평균 대여 기간 >= 7일, 소수점 두번째 자리 반올림
-- 평균 대여 기간 기준 내림차순 -> 자동차 ID 내림차순
SELECT CAR_ID, 
ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;